---
# yamllint disable rule:line-length
project:
  name: nuragoexample
  title: nuragoexample
  category: Application
  copyright_start_year: "2025"
  copyright_owner: nuragoexampleowner
  license_url: https://github.com/nuragoexampleowner/nuragoexample/blob/main/LICENSE
  cvs: https://github.com/nuragoexampleowner/nuragoexample
  tagline: nuragoexampleshortdesc
  logo: doc/images/logo.png
team:
  name: nuragoexampleowner
  title: nuragoexampleowner
  info:
  slack:
  escalation:
attachments:
doclinks:
  public:
    general:
      name: General
      description: General project documentation
      links:
        github:
          name: GitHub project page
          url: nuragoexampleprojectlink
slack:
dependencies:
environment:
