{
 "title": "GOGENEXAMPLE",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "tags": [
  "oss",
  "gogenexample",
  "golang",
  "go",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "dc",
    "query": "label_values(go_memstats_alloc_bytes, dc)"
   },
   {
    "name": "instance",
    "query": "label_values(go_memstats_alloc_bytes, instance)"
   },
   {
    "name": "port",
    "query": "label_values(go_memstats_alloc_bytes, port)"
   },
   {
    "name": "method",
    "query": "label_values(request_duration_seconds_sum, method)"
   },
   {
    "name": "handler",
    "query": "label_values(request_duration_seconds_sum, handler)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "graph",
   "description": "Average response time for inbound requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\",method=~\"^($method)$\",handler=~\"^($handler)$\"}[$__interval])) / sum(rate(request_duration_seconds_count{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\",method=~\"^($method)$\",handler=~\"^($handler)$\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Error codes",
   "type": "graph",
   "description": "Internal error by tasks, codes and operations (steps).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (task, operation, code) (increase(error_code_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\"}))",
     "legendFormat": "{{task}} - {{operation}} - {{code}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Logs by Level",
   "type": "graph",
   "description": "Number of logs grouped by standard syslog level.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (rate(log_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "Inbound HTTP Requests",
   "type": "graph",
   "description": "Inbound HTTP requests grouped by method and endpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method,handler) (rate(increase(request_duration_seconds_count{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\",method=~\"^($method)$\",handler=~\"^($handler)$\"}[$__interval])))",
     "legendFormat": "{{method}}:{{handler}}"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "Inbound HTTP status codes per second",
   "type": "graph",
   "description": "Number of inbound requests per seconds grouped by HTTP status code.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(rate(api_requests_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}} - virtual"
    }
   ]
  },
  {
   "title": "Average Inbound Request Size [byte/second]",
   "type": "graph",
   "description": "Average Inbound request size in [byte/second]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(request_size_bytes_sum{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval]))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - virtual"
    }
   ]
  },
  {
   "title": "Average Inbound Response Size [byte/second]",
   "type": "graph",
   "description": "Average Inbound response size in [byte/second]",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(response_size_bytes_sum{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval]))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound HTTP Requests",
   "type": "graph",
   "description": "Outbound HTTP requests grouped by status code and method.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code,method) (rate(increase(outbound_request_duration_seconds_count{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\",method=~\"^($method)$\",handler=~\"^($handler)$\"}[$__interval])))",
     "legendFormat": "{{code}}:{{method}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound HTTP status codes per second",
   "type": "graph",
   "description": "Number of outbound requests per seconds grouped by HTTP status code.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(rate(outbound_requests_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=\"gogenexample-monitoring\",port=~\"^($port)$\"}[$__interval])",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  }
 ]
}