{
 "title": "~#UPROJECT#~",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "dc",
    "query": "label_values(go_memstats_alloc_bytes, dc)"
   },
   {
    "name": "instance",
    "query": "label_values(go_memstats_alloc_bytes, instance)"
   },
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes, job)"
   },
   {
    "name": "port",
    "query": "label_values(go_memstats_alloc_bytes, port)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "method",
    "query": "label_values(request_duration_seconds_sum, method)"
   },
   {
    "name": "handler",
    "query": "label_values(request_duration_seconds_sum, handler)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(deriv(request_duration_seconds_sum{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",method=~\"^($method)$\",handler=~\"^($handler)$\"}[30s]))"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[$interval])",
     "legendFormat": "{{instance}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[$interval])",
     "legendFormat": "{{instance}} - virtual"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(request_duration_seconds_count{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",method=~\"^($method)$\",handler=~\"^($handler)$\"}[30s])",
     "legendFormat": "{{method}}:{{handler}}"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[$interval])",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[$interval])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[$interval])",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[$interval])",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"debug\"}[1m]))",
     "legendFormat": "debug"
    },
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"info\"}[1m]))",
     "legendFormat": "info"
    },
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"notice\"}[1m]))",
     "legendFormat": "notice"
    },
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"warning\"}[1m]))",
     "legendFormat": "warning"
    },
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"error\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"crit\"}[1m]))",
     "legendFormat": "critical"
    },
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"alert\"}[1m]))",
     "legendFormat": "alert"
    },
    {
     "expr": "sum(deriv(error_level_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\",level=\"emergency\"}[1m]))",
     "legendFormat": "emergency"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}}: {{quantile}}"
    }
   ]
  },
  {
   "title": "HTTP status codes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(api_requests_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\", code=~\"2..\"}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(deriv(api_requests_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\", code=~\"3..\"}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(deriv(api_requests_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\", code=~\"4..\"}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(deriv(api_requests_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\", code=~\"5..\"}[1m]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}[30s])",
     "legendFormat": "{{instance}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{dc=~\"^($dc)$\",instance=~\"^($instance)$\",job=~\"^($job)$\",port=~\"^($port)$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}