package random

import (
	"time"

	"github.com/tecnickcom/gogen/pkg/uhex"
)

// UUID is a 128-bit (16-byte) Universally Unique Identifier (UUID)
// as defined in RFC 9562 (https://datatracker.ietf.org/doc/html/rfc9562).
//
// UUIDs are commonly used to uniquely identify resources, records, or entities
// in distributed systems without requiring centralized coordination.
// This type represents the binary form; use String() or Byte() to get the standard
// textual representation in the format "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx".
type UUID [16]byte

const (
	// uuidSep is the character used as separator between UUID sections.
	uuidSep = '-'
)

// UUIDv7 generates a 128-bit RFC 9562 UUID version 7 (time-based with random).
//
// UUIDs generated by this function are suitable for distributed, unique identification
// with the following properties:
//   - Timestamp component (48 bits): millisecond-precision Unix epoch time
//   - Random component (80 bits): pseudorandom data for uniqueness and collision avoidance
//   - Sortable: UUIDs generated at later times have higher values (useful for database indexing)
//   - Cryptographically strong randomness is not guaranteed; use only for non-cryptographic purposes
//
// The function returns the UUID in binary form. Use String() or Byte() to get
// the standard human-readable format.
func (r *Rnd) UUIDv7() UUID {
	var ub UUID

	now := time.Now()
	ms := now.UnixMilli()

	// unix_ts_ms:
	// 48-bit big-endian unsigned number of the Unix Epoch timestamp in milliseconds
	// bits 0 through 47 (octets 0-5)
	ub[0] = byte(ms >> 40)
	ub[1] = byte(ms >> 32)
	ub[2] = byte(ms >> 24)
	ub[3] = byte(ms >> 16)
	ub[4] = byte(ms >> 8)
	ub[5] = byte(ms)

	// approximate map remaining nanoseconds in the range [0, 4095]
	// Note:
	// 4294 = (4095 * 2^20) / 1,000,000
	// shifting right by 20 bits is roughly equivalent to dividing byiding by 1,048,576.
	ns := ((now.Nanosecond() % 1e6) * 4294) >> 20

	// ver:
	// 4-bit version field set to 0b0111 (7)
	// bits 48 through 51 of octet 6
	// +
	// rand_a:
	// 12 bits of pseudorandom data
	// bits 52 through 63 (octets 6-7)
	ub[6] = 0x70 | (0x0F & byte(ns>>8))
	ub[7] = byte(ns)

	// generate 8 random bytes
	rb, _ := r.RandomBytes(8)

	// var:
	// 2-bit variant field set to 0b10
	// bits 64 and 65 of octet 8.
	// +
	// rand_b:
	// 62 bits of pseudorandom data to provide uniqueness
	// bits 66 through 127 (octets 8-15).
	ub[8] = 0x80 | (0x3F & rb[0])
	copy(ub[9:16], rb[1:8])

	return ub
}

// Format writes the UUID in standard textual format to dst.
//
// The output format is: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" (36 characters)
// where each 'x' is a lowercase hexadecimal digit.
//
// Use this method when you need to write the UUID directly into a pre-allocated buffer
// for performance-critical code. For general-purpose use, prefer String() which returns
// a Go string, or Byte() which returns a slice.
func (u UUID) Format(dst *[36]byte) {
	uuid := dst[:]

	uhex.Hex32BB(*(*[4]byte)(u[0:4]), (*[8]byte)(uuid[0:8]))
	uuid[8] = uuidSep
	uhex.Hex16BB(*(*[2]byte)(u[4:6]), (*[4]byte)(uuid[9:13]))
	uuid[13] = uuidSep
	uhex.Hex16BB(*(*[2]byte)(u[6:8]), (*[4]byte)(uuid[14:18]))
	uuid[18] = uuidSep
	uhex.Hex16BB(*(*[2]byte)(u[8:10]), (*[4]byte)(uuid[19:23]))
	uuid[23] = uuidSep
	uhex.Hex32BB(*(*[4]byte)(u[10:14]), (*[8]byte)(uuid[24:32]))
	uhex.Hex16BB(*(*[2]byte)(u[14:16]), (*[4]byte)(uuid[32:36]))
}

// Byte returns the UUID as a 36-byte slice in the standard textual format.
//
// The output is: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" (36 characters)
// where each character is a lowercase hexadecimal digit.
//
// Each call to Byte() allocates a new [36]byte array. Use String() if you need
// a Go string instead of a byte slice, or Format() for maximum performance
// if you already have a pre-allocated buffer.
func (u UUID) Byte() []byte {
	var b [36]byte
	u.Format(&b)

	return b[:]
}

// String returns the UUID as a standard 36-character string.
//
// The output is: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
// where each character is a lowercase hexadecimal digit.
//
// This is the preferred method for most use cases (logging, JSON marshaling, display).
// Use Byte() if you need a byte slice, or Format() if working with pre-allocated buffers
// in performance-critical code.
func (u UUID) String() string {
	return string(u.Byte())
}
