package random

import (
	"encoding/binary"
	mrand "math/rand/v2"
	"time"

	"github.com/tecnickcom/nurago/pkg/uhex"
)

// UUID is a 128-bit (16-byte) Universally Unique Identifier (UUID)
// as defined in RFC 9562 (https://datatracker.ietf.org/doc/html/rfc9562).
//
// UUIDs are commonly used to uniquely identify resources, records, or entities
// in distributed systems without requiring centralized coordination.
// This type represents the binary form; use String() or Byte() to get the standard
// textual representation in the format "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx".
type UUID [16]byte

const (
	// uuidSep is the character used as separator between UUID sections.
	uuidSep = '-'
)

// UUIDv7 generates a 128-bit RFC 9562 UUID version 7 (time-based with random).
//
// UUIDs generated by this function are suitable for distributed, unique identification
// with the following properties:
//   - Timestamp component (48 bits): millisecond-precision Unix epoch time
//   - Sub-millisecond clock precision (12 bits, rand_a): the nanosecond remainder
//     of the current millisecond, scaled into [0, 4095]. This is RFC 9562 §6.2
//     Method 3 ("Replace Leftmost Random Bits with Increased Clock Precision"),
//     and it is what makes values generated within the same millisecond sortable.
//     These bits are clock-derived, not random.
//   - Random component (62 bits, rand_b): pseudorandom data for uniqueness and
//     collision avoidance. 62 is the total random bit count of the value: the
//     version (4 bits) and variant (2 bits) are fixed, and rand_a is clock-derived.
//   - Sortable: UUIDs generated at later times have higher values (useful for database indexing)
//   - Cryptographically strong randomness is not guaranteed; use only for non-cryptographic purposes
//
// The function returns the UUID in binary form. Use String() or Byte() to get
// the standard human-readable format.
//
// Performance:
//   - Each call makes a single small heap allocation for the random bytes. This
//     is structural: randomness is read through the configurable [io.Reader], so
//     the compiler cannot keep the buffer on the stack. The 16-byte UUID itself
//     is stack-allocated and returned by value.
//   - Per-call cost is dominated by two largely irreducible operations: reading
//     the wall clock ([time.Now]) and reading random bytes from the reader
//     (crypto/rand by default). It draws only the 8 random bytes it needs (the
//     62-bit rand_b field, which spans octets 8-15; the 2 variant bits are
//     overwritten with constants), rather than generating a full 16 random bytes
//     and overwriting the timestamp octets as a naive v7 construction does, so it
//     reads half the entropy; the bit-packing and version/variant masking are
//     negligible by comparison.
//   - The function holds no shared mutable state and takes no locks of its own,
//     so a single [Rnd] is safe for concurrent use and callers are not
//     serialized; concurrent throughput is bounded by the configured reader
//     rather than by this function. Ordering of values generated within the same
//     sub-millisecond instant is statistical, not strictly monotonic; that is
//     the trade that keeps the path lock-free.
//   - For the textual form, [UUID.Format] builds the canonical string with
//     table-driven lookups instead of reflection-based formatting such as
//     [fmt.Sprintf]: it writes into a caller-owned buffer without allocating.
//     [UUID.String] always allocates once for its result; [UUID.Byte] allocates
//     its [36]byte only when the returned slice escapes the caller, and is free
//     when it does not. Prefer Format in hot paths; see [UUID.Format] for the
//     comparison with the standard-library encoders.
//
// These are qualitative characteristics, not guarantees; absolute costs depend
// on hardware, the Go compiler, and the configured reader. Run the package
// benchmarks (go test -bench=.) to measure on a target platform.
func (r *Rnd) UUIDv7() UUID {
	var ub UUID

	now := time.Now()
	ms := now.UnixMilli()

	// unix_ts_ms:
	// 48-bit big-endian unsigned number of the Unix Epoch timestamp in milliseconds
	// bits 0 through 47 (octets 0-5)
	ub[0] = byte(ms >> 40)
	ub[1] = byte(ms >> 32)
	ub[2] = byte(ms >> 24)
	ub[3] = byte(ms >> 16)
	ub[4] = byte(ms >> 8)
	ub[5] = byte(ms)

	// approximate map remaining nanoseconds in the range [0, 4095]
	// Note:
	// 4294 = (4095 * 2^20) / 1,000,000
	// shifting right by 20 bits is roughly equivalent to dividing by 1,048,576.
	// The multiplication is widened to int64 because the intermediate product can
	// reach 999999*4294 = 4293995706, which does not fit in a 32-bit int. The 12
	// bits actually emitted would in fact survive the overflow (it wraps by exactly
	// 2^32, and (x-2^32)>>20 == (x>>20)-4096, which is invisible modulo 4096), but
	// relying on that would make the intermediate value meaningless on a 32-bit
	// platform and the code impossible to read. Keep the widening.
	ns := int((int64(now.Nanosecond()%1e6) * 4294) >> 20)

	// ver:
	// 4-bit version field set to 0b0111 (7)
	// bits 48 through 51 of octet 6
	// +
	// rand_a:
	// 12 bits of increased clock precision (RFC 9562 6.2, Method 3), not random
	// data: ns above. This is what orders values generated within the same
	// millisecond.
	// bits 52 through 63 (octets 6-7)
	ub[6] = 0x70 | (0x0F & byte(ns>>8))
	ub[7] = byte(ns)

	// Read the 8 random bytes directly, bypassing the RandomBytes wrapper (a
	// function call plus error-wrapping path) on this hot path. rb is heap-allocated
	// rather than stack-local: the read goes through the configurable io.Reader, so
	// escape analysis cannot keep the buffer on the stack.
	//
	// On reader failure fall back to math/rand/v2 directly, so this never panics.
	// Going through RandUint64 here would re-read from the reader that just failed,
	// paying a second allocation and a second failing read before landing on the
	// same fallback.
	var rb [8]byte

	err := readFull(r.reader, rb[:])
	if err != nil {
		r.notifyFallback()

		binary.LittleEndian.PutUint64(rb[:], mrand.Uint64()) //nolint:gosec
	}

	// var:
	// 2-bit variant field set to 0b10
	// bits 64 and 65 of octet 8.
	// +
	// rand_b:
	// 62 bits of pseudorandom data to provide uniqueness
	// bits 66 through 127 (octets 8-15).
	ub[8] = 0x80 | (0x3F & rb[0])
	copy(ub[9:16], rb[1:8])

	return ub
}

// Format writes the UUID in standard textual format to dst.
//
// The output format is: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" (36 characters)
// where each 'x' is a lowercase hexadecimal digit.
//
// Use this method when you need to write the UUID directly into a pre-allocated buffer
// for performance-critical code. For general-purpose use, prefer String() which returns
// a Go string, or Byte() which returns a slice.
//
// Performance:
// Format builds the canonical text with the table-driven [uhex] encoders instead
// of reflection-based formatting. Each byte is translated through a 256-entry
// lookup table and written with a single 16-bit store, so the routine is fully
// unrolled, branch-free, independent of the UUID value, and writes into the
// caller's array without allocating. Against the usual standard-library ways of
// producing the same string this is markedly cheaper: versus
// [fmt.Sprintf]("%x-%x-%x-%x-%x", …) it is well over an order of magnitude faster
// (~40x on amd64) and avoids the reflection-driven allocations, and versus
// [encoding/hex] plus manual separator insertion it is roughly 2-3x faster,
// though both write into a caller-owned buffer without allocating.
// [UUID.String] and [UUID.Byte] layer a single result allocation on top of this.
func (u UUID) Format(dst *[36]byte) {
	uuid := dst[:]

	uhex.Hex32BB(*(*[4]byte)(u[0:4]), (*[8]byte)(uuid[0:8]))
	uuid[8] = uuidSep
	uhex.Hex16BB(*(*[2]byte)(u[4:6]), (*[4]byte)(uuid[9:13]))
	uuid[13] = uuidSep
	uhex.Hex16BB(*(*[2]byte)(u[6:8]), (*[4]byte)(uuid[14:18]))
	uuid[18] = uuidSep
	uhex.Hex16BB(*(*[2]byte)(u[8:10]), (*[4]byte)(uuid[19:23]))
	uuid[23] = uuidSep
	uhex.Hex32BB(*(*[4]byte)(u[10:14]), (*[8]byte)(uuid[24:32]))
	uhex.Hex16BB(*(*[2]byte)(u[14:16]), (*[4]byte)(uuid[32:36]))
}

// Byte returns the UUID as a 36-byte slice in the standard textual format.
//
// The output is: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" (36 characters)
// where each character is a lowercase hexadecimal digit.
//
// Byte fills a local [36]byte array and returns a slice over it, so whether it
// allocates depends on escape analysis at the call site: if the returned slice
// does not escape the caller (it is read and discarded, or only its bytes are
// consumed), the array stays on the stack and no allocation occurs; if it escapes
// (stored, returned, sent on a channel, or passed to a function the compiler
// cannot inline), the array is heap-allocated. Use String() if you need a Go
// string instead of a byte slice, or Format() to write into a pre-allocated
// buffer and never allocate regardless of escape analysis.
func (u UUID) Byte() []byte {
	var b [36]byte
	u.Format(&b)

	return b[:]
}

// String returns the UUID as a standard 36-character string.
//
// The output is: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
// where each character is a lowercase hexadecimal digit.
//
// This is the preferred method for most use cases (logging, JSON marshaling, display).
// Use Byte() if you need a byte slice, or Format() if working with pre-allocated buffers
// in performance-critical code.
func (u UUID) String() string {
	return string(u.Byte())
}
