#!/bin/sh

# Check if the VERSION has been updated before pushing to the master branch.
#
# @author      Nicola Asuni <info@tecnick.com>

# current git branch
CURRENT_GIT_BRANCH=`git rev-parse --abbrev-ref HEAD`

# if we are in the main branch, then check if the version has been updated
if [ "${CURRENT_GIT_BRANCH}" = "master" ]; then
	VERSION_DIFF=`git diff origin/master -- VERSION | tail -2`
	if [ "${VERSION_DIFF}" = "" ]; then
		echo >&2 "ERROR: The version in the VERSION file has not been updated!"
		exit 1
	else
		# check if the vesion number has been incremented
		OLD_VERSION=`echo $VERSION_DIFF | grep -Po "[-]\K([^ ]+)" | gawk -F. '{ printf("%03d%03d%06d\n", $1,$2,$3); }'`
		NEW_VERSION=`echo $VERSION_DIFF | grep -Po "[+]\K([^ ]+)" | gawk -F. '{ printf("%03d%03d%06d\n", $1,$2,$3); }'`
		if [ $OLD_VERSION -gt $NEW_VERSION ]; then
			echo >&2 "ERROR: The version in the VERSION file must be greater than the previous one!"
			exit 1
		fi
	fi
	make qa
fi

exit 0
