.\" Manpage for gogenexample.
.TH GOGENEXAMPLE "1" "2020" "gogenexample" "User Commands"
.SH NAME
gogenexample \- gogenexampleshortdesc
.SH DESCRIPTION
gogenexamplelongdesc
.SS "Usage:"
.IP
gogenexample [flags]
gogenexample [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-c\fR, \fB\-\-configDir\fR=\fI10\fR: Configuration directory to be added on top of the search list
.HP
\fB\-f\fR, \fB\-\-logFormat\fR=\fI10\fR: Logging format: CONSOLE, JSON
.HP
\fB\-o\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: EMERGENCY, ALERT, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
.PP
Use "gogenexample [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
Author (gogenexampleemail)
.SH COPYRIGHT
(c) 2020 gogenexampleauthor
