.\" Manpage for nuragoexample.
.TH NURAGOEXAMPLE "1" "2020" "nuragoexample" "User Commands"
.SH NAME
nuragoexample \- nuragoexampleshortdesc
.SH DESCRIPTION
nuragoexamplelongdesc
.SS "Usage:"
.IP
nuragoexample [flags]
nuragoexample [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-c\fR, \fB\-\-configDir\fR=\fI10\fR: Configuration directory to be added on top of the search list
.HP
\fB\-f\fR, \fB\-\-logFormat\fR=\fI10\fR: Logging format: CONSOLE, JSON
.HP
\fB\-o\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: EMERGENCY, ALERT, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
.PP
Use "nuragoexample [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
Author (nuragoexampleemail)
.SH COPYRIGHT
(c) 2020 nuragoexampleauthor
