-- Create the R/W role
CREATE ROLE dbrw_user WITH LOGIN PASSWORD 'dbrw_pass';
GRANT USAGE ON SCHEMA public TO dbrw_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dbrw_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO dbrw_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dbrw_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO dbrw_user;

-- Create the R/O role
CREATE ROLE dbro_user WITH LOGIN PASSWORD 'dbro_pass';
GRANT USAGE ON SCHEMA public TO dbro_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbro_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dbro_user;
