.\" Manpage for ~#PROJECT#~.
.TH ~#UPROJECT#~ "1" "~#CURRENTYEAR#~" "~#PROJECT#~" "User Commands"
.SH NAME
~#PROJECT#~ \- ~#SHORTDESCRIPTION#~
.SH DESCRIPTION
~#PROJECT#~ ~#SHORTDESCRIPTION#~
.SS "Usage:"
.IP
~#PROJECT#~ [flags]
~#PROJECT#~ [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-u\fR, \fB\-\-serverAddress\fR=\fI10\fR: HTTP API address for server mode (ip:port) or just (:port)
.HP
\fB\-p\fR, \fB\-\-statsPrefix\fR=\fI10\fR: StatsD bucket prefix name
.HP
\fB\-k\fR, \fB\-\-statsNetwork\fR=\fI10\fR: StatsD client network type (udp or tcp)
.HP
\fB\-m\fR, \fB\-\-statsAddress\fR=\fI10\fR: StatsD daemon address (ip:port) or just (:port)
.HP
\fB\-r\fR, \fB\-\-statsFlushPeriod\fR=\fI10\fR: StatsD client flush period in milliseconds
.HP
\fB\-o\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: panic, fatal, error, warning, info, debug
.PP
Use "~#PROJECT#~ [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
~#OWNER#~ (~#OWNEREMAIL#~)
.SH COPYRIGHT
(c) ~#CURRENTYEAR#~ ~#OWNER#~
