.\" Manpage for ~#PROJECT#~.
.TH ~#UPROJECT#~ "1" "~#CURRENTYEAR#~" "~#PROJECT#~" "User Commands"
.SH NAME
~#PROJECT#~ \- ~#SHORTDESCRIPTION#~
.SH DESCRIPTION
~#PROJECT#~ ~#SHORTDESCRIPTION#~
.SS "Usage:"
.IP
~#PROJECT#~ [flags]
~#PROJECT#~ [command]
.SS "Available Commands:"
.TP
version
print this program version
.SS "Flags:"
.HP
\fB\-c\fR, \fB\-\-configDir\fR=\fI10\fR: Configuration directory to be added on top of the search list
.HP
\fB\-o\fR, \fB\-\-logLevel\fR=\fI10\fR: Log level: panic, fatal, error, warning, info, debug
.HP
\fB\-q\fR, \fB\-\-quantity\fR=\fI10\fR: NUmber of results to return
.PP
Use "~#PROJECT#~ [command] \fB\-\-help\fR" for more information about a command.
.SH AUTHOR
~#OWNER#~ (~#OWNEREMAIL#~)
.SH COPYRIGHT
(c) ~#CURRENTYEAR#~ ~#OWNER#~
